# Generated by Django 5.1.5 on 2025-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=200, unique=True)),
                ('league', models.CharField(default='', max_length=100, unique=True)),
                ('score', models.IntegerField(default=1)),
            ],
        ),
    ]
