# Generated by Django 5.1.5 on 2025-01-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_team_teams_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
        migrations.AddField(
            model_name='teams',
            name='avg_score',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='teams',
            name='opp_avg_score',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
